#!/usr/bin/env python3
"""Regenerate summary.md for the currently-open task.

"Open task" = whichever taskId was most recently set as open by
restore / checkpoint / relocate_plan. If no task is open, print a hint
pointing the user at /restore.

For tasks whose plan.md is a script-generated metadata stub
(``source: checkpoint`` + ``trigger: auto``), the plan.md is first
re-populated from the relevant slice of the Claude Code session JSONL
between the previous task's ``created_at`` and this task's
``created_at``. That gives the async summary worker actual conversation
content to summarize. plan.md generated by Claude (manual checkpoint or
any other source) is left untouched.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import _common  # noqa: E402


def _hint_when_no_open_task(project: str) -> None:
    print("**現在開いている task はありません。**")
    print()
    print("先に `/cc-workflow:restore <taskId>` で task を読み込んでから、")
    print("`/cc-workflow:summarise` を実行してください。")
    print()
    print(f"プロジェクト `{project}` の taskId は `/cc-workflow:tasks` で確認できます。")


def _enrich_plan_with_session_slice(task_dir: Path, project_root: Path) -> bool:
    """If this task is an auto-checkpoint, overwrite plan.md with the
    conversation slice from JSONL between prev task and this task.
    Returns True when plan.md was overwritten."""
    fm = _common.parse_frontmatter(task_dir / "task.md")
    if fm.get("source") != "checkpoint" or fm.get("trigger") != "auto":
        return False

    sid = fm.get("session_id", "")
    if not sid:
        return False
    this_created = fm.get("created_at", "")

    # Resolve previous task's created_at
    prev_id = fm.get("prev_task_id", "")
    after_iso = ""
    if prev_id:
        prev_dir = task_dir.parent / prev_id
        prev_fm = _common.parse_frontmatter(prev_dir / "task.md")
        after_iso = prev_fm.get("created_at", "")

    transcript = _common.session_transcript_path(sid, project_root)
    slice_md = _common.extract_session_slice(
        transcript_path=transcript,
        session_id=sid,
        after_iso=after_iso,
        before_iso=this_created,
    )
    if not slice_md.strip():
        return False

    header_lines = [
        f"# {task_dir.name}",
        "",
        f"_(自動 checkpoint。`/summarise` 実行時に JSONL から会話履歴を抜き出して plan.md を更新した。)_",
        "",
        f"- 元 session_id: `{sid}`",
        f"- 抜粋範囲: `{after_iso or '(セッション開始)'}` 〜 `{this_created}`",
        "",
        "## 会話履歴 (user / assistant)",
        "",
    ]
    (task_dir / "plan.md").write_text(
        "\n".join(header_lines) + slice_md + "\n", encoding="utf-8"
    )
    return True


def main() -> int:
    sid = _common.detect_current_session_id()
    project, project_root = _common.get_project_info(session_id=sid)

    if not sid:
        _hint_when_no_open_task(project)
        return 0

    taskid = _common.read_open_task(session_id=sid)
    if not taskid:
        _hint_when_no_open_task(project)
        return 0

    task_dir = _common.project_tasks_dir(project) / taskid
    if not task_dir.is_dir():
        print(
            f"開いていた taskId `{taskid}` がプロジェクト `{project}` に見つかりません。"
        )
        print(
            "`/cc-workflow:tasks` で一覧を見て、改めて "
            "`/cc-workflow:restore <taskId>` してください。"
        )
        return 0

    plan_path = task_dir / "plan.md"
    if not plan_path.is_file():
        print(f"plan.md が見つかりません: `{plan_path}`")
        return 0

    enriched = _enrich_plan_with_session_slice(task_dir, project_root)

    summary_path = task_dir / "summary.md"
    summary_path.write_text("_(要約を再生成中…)_\n", encoding="utf-8")

    _common.spawn_detached(
        [
            _common.python_executable(),
            str(Path(__file__).parent / "_summarize_worker.py"),
            str(plan_path),
            str(summary_path),
        ]
    )

    print(f"taskId `{taskid}` の要約ワーカーをバックグラウンド起動しました。")
    if enriched:
        print("（自動 checkpoint だったため、JSONL の会話履歴を plan.md に書き込んでから要約します）")
    print(f"- 数十秒で更新されます: `{summary_path}`")
    return 0


if __name__ == "__main__":
    sys.exit(main())
